#!/bin/bash
# kanban-create.sh — Create a kanban card via the Command Center API
#
# Usage:
#   kanban-create.sh <type> <title> [description] [priority]
#
# Types: task, goal, idea
# Priority: urgent, normal (default: urgent)
#
# Examples:
#   kanban-create.sh task "Fix login bug" "Login throws 500 on Safari" urgent
#   kanban-create.sh task "Update docs"

TYPE="${1:-}"
TITLE="${2:-}"
DESCRIPTION="${3:-}"
PRIORITY="${4:-urgent}"

if [ -z "$TYPE" ] || [ -z "$TITLE" ]; then
  echo "Usage: kanban-create.sh <type> <title> [description] [priority]" >&2
  echo "Types: task, goal, idea" >&2
  echo "Priority: urgent, normal (default: urgent)" >&2
  exit 1
fi

API="http://localhost:3001/api/kanban"

# Duplicate guardrail:
# Prevent re-creating items that already exist anywhere on the board
# (ideas/goals/todo/in_progress/blocked/review/done/rejected/test columns).
# Override intentionally with: KANBAN_ALLOW_DUPLICATE=1 ./kanban-create.sh ...
if [ "${KANBAN_ALLOW_DUPLICATE:-0}" != "1" ]; then
  BOARD_JSON=$(curl -s "$API")
  DUPLICATE_HIT=$(printf "%s" "$BOARD_JSON" | python3 -c '
import json, re, sys

def norm(s: str) -> str:
    s = (s or "").strip().lower()
    s = re.sub(r"[^a-z0-9]+", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

try:
    data = json.load(sys.stdin)
except Exception:
    print("")
    raise SystemExit(0)

target = norm(sys.argv[1])
columns = data.get("columns", {}) if isinstance(data, dict) else {}
all_cols = [
    "ideas", "goals", "todo", "in_progress", "blocked",
    "review", "done", "rejected", "msl_test", "msl_done", "cuu_test", "cuu_done"
]

for col in all_cols:
    for card in columns.get(col, []) or []:
        existing = norm(card.get("title", ""))
        if existing and existing == target:
            print("{}:{}".format(col, card.get("id", "unknown")))
            raise SystemExit(0)

print("")
' "$TITLE")

  if [ -n "$DUPLICATE_HIT" ]; then
    COL="${DUPLICATE_HIT%%:*}"
    CARD_ID="${DUPLICATE_HIT#*:}"
    echo "SKIP: Duplicate title already exists in '$COL' ($CARD_ID): $TITLE" >&2
    exit 2
  fi
fi

JSON=$(python3 -c "
import json, sys
print(json.dumps({
    'type': sys.argv[1],
    'title': sys.argv[2],
    'description': sys.argv[3],
    'priority': sys.argv[4]
}))
" "$TYPE" "$TITLE" "$DESCRIPTION" "$PRIORITY")

RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$API" \
  -H "Content-Type: application/json" \
  -d "$JSON")

HTTP_CODE=$(echo "$RESPONSE" | tail -1)
BODY=$(echo "$RESPONSE" | sed '$d')

if [ "$HTTP_CODE" = "201" ] || [ "$HTTP_CODE" = "200" ]; then
  CARD_ID=$(echo "$BODY" | python3 -c "import json,sys; print(json.load(sys.stdin).get('id','unknown'))" 2>/dev/null)

  # Auto-create HAL context handoff file for faster task pickup.
  HANDOFF_DIR="$HOME/.openclaw/workspace/goals/handoffs"
  CONTEXT_FILE="$HANDOFF_DIR/hal-context-${CARD_ID}.md"
  mkdir -p "$HANDOFF_DIR"
  cat > "$CONTEXT_FILE" <<EOF
# HAL Context — ${CARD_ID}

## Card
- ID: ${CARD_ID}
- Type: ${TYPE}
- Priority: ${PRIORITY}
- Title: ${TITLE}

## Description
${DESCRIPTION}

## Initial Deliverables Checklist
- [ ] Confirm understanding of objective
- [ ] List exact files to touch
- [ ] Define validation command(s)
- [ ] Note rollback/safety plan for non-trivial changes

## Notes
- Auto-generated by scripts/kanban-create.sh
- Update this file before HAL dispatch when more context is available.
EOF

  echo "OK: Created $TYPE '$TITLE' ($CARD_ID) with priority $PRIORITY"
  echo "OK: Created HAL context file: $CONTEXT_FILE"
  echo "$CARD_ID"
  exit 0
else
  echo "ERROR: HTTP $HTTP_CODE -- $BODY" >&2
  exit 1
fi
