#!/bin/bash
# weekly-digest.sh — Generate Weekly Wins & Impact Digest and post to Discord
#
# Usage:
#   bash weekly-digest.sh              # Normal weekly run
#   bash weekly-digest.sh --dry-run    # Print digest to stdout, don't post
#
# Posts to: Discord webhook
# Cron:     Fridays 6 PM AST (22:00 UTC) via jobs.json

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

DISCORD_WEBHOOK="https://discord.com/api/webhooks/1476444786465570978/Tf2rnq-ALVx39V3EiLJTqmI5E4uuyN-1mwZw_2iG0pvISpKiZvEU_drgbxonvmZ0bMnR"
KANBAN_API="http://localhost:3001/api/kanban"
SINCE_DAYS=7
TMPDIR_LOCAL=$(mktemp -d)
trap 'rm -rf "$TMPDIR_LOCAL"' EXIT

KANBAN_FILE="$TMPDIR_LOCAL/kanban.json"
PAYLOAD_FILE="$TMPDIR_LOCAL/payload.json"

# ─── Fetch Kanban data ────────────────────────────────────────────────────────
curl -s "$KANBAN_API" > "$KANBAN_FILE" 2>/dev/null || {
  echo "ERROR: Failed to fetch Kanban data" >&2
  exit 1
}

# ─── Collect git activity ─────────────────────────────────────────────────────
GIT_LINES=""
for REPO in "$HOME/market-signal-lab" "$HOME/command-center"; do
  REPO_NAME=$(basename "$REPO")
  if [ -d "$REPO/.git" ]; then
    COUNT=$(git -C "$REPO" log --oneline --since="${SINCE_DAYS} days ago" 2>/dev/null | wc -l | tr -d ' ')
    if [ "$COUNT" -gt "0" ]; then
      COMMITS=$(git -C "$REPO" log --oneline --since="${SINCE_DAYS} days ago" 2>/dev/null | head -3 | sed 's/^[a-f0-9]* //')
      GIT_LINES="${GIT_LINES}**${REPO_NAME}** (${COUNT} commits)\n"
      while IFS= read -r line; do
        GIT_LINES="${GIT_LINES}• ${line}\n"
      done <<< "$COMMITS"
    fi
  fi
done

# ─── Build Discord payload via Python ────────────────────────────────────────
WEEK_END=$(date '+%b %d')
WEEK_START=$(date -v-${SINCE_DAYS}d '+%b %d' 2>/dev/null || date -d "${SINCE_DAYS} days ago" '+%b %d' 2>/dev/null || echo "this week")

python3 - "$KANBAN_FILE" "$WEEK_START" "$WEEK_END" "$SINCE_DAYS" "$PAYLOAD_FILE" <<'PYEOF'
import json, sys
from datetime import datetime, timedelta, timezone

kanban_file, week_start, week_end, since_days_str, payload_file = sys.argv[1:]
since_days = int(since_days_str)

with open(kanban_file) as f:
    data = json.load(f)

since = datetime.now(timezone.utc) - timedelta(days=since_days)
columns = data.get("columns", {})

# Shipped cards
done_items, review_items = [], []
for col, bucket in [("done", done_items), ("review", review_items)]:
    for card in columns.get(col, []):
        updated = card.get("updatedAt", "")
        try:
            dt = datetime.fromisoformat(updated.replace("Z", "+00:00"))
            if dt >= since:
                bucket.append(card["title"])
        except Exception:
            pass

# In-progress
in_progress = [c["title"] for c in columns.get("in_progress", [])]
# Blocked
blocked = [c["title"] for c in columns.get("blocked", [])]
# Stats
stats = {
    "done": len(columns.get("done", [])),
    "review": len(columns.get("review", [])),
    "in_progress": len(columns.get("in_progress", [])),
    "todo": len(columns.get("todo", []))
}

def build_section(done, review):
    lines = []
    for t in done:
        lines.append(f"✅ {t}")
    for t in review:
        lines.append(f"🔍 {t} *(in review)*")
    return "\n".join(lines) if lines else "_Nothing moved to done/review this week_"

def build_list(items, emoji):
    if not items:
        return f"_None — clean week_ ✨"
    return "\n".join(f"{emoji} {t}" for t in items)

shipped_text = build_section(done_items, review_items)
progress_text = build_list(in_progress, "🔄")
blocked_text = build_list(blocked, "🚧")

board_health = (
    f"📋 Board: **{stats['done']}** done · **{stats['review']}** in review · "
    f"**{stats['in_progress']}** active · **{stats['todo']}** queued"
)

embed = {
    "username": "Alfred 🎩",
    "embeds": [
        {
            "title": "📊 Weekly Wins & Impact Digest",
            "description": f"**{week_start} – {week_end}** · Auto-generated by Alfred\n\n{board_health}",
            "color": 5814783,
            "fields": [
                {"name": "🚀 Shipped This Week", "value": shipped_text[:1020], "inline": False},
                {"name": "🔄 In Progress", "value": progress_text[:1020], "inline": True},
                {"name": "🚧 Blockers", "value": blocked_text[:1020], "inline": True},
            ],
            "footer": {"text": "Alfred · Weekly Digest · Every Friday 6 PM AST"}
        }
    ]
}

with open(payload_file, "w") as f:
    json.dump(embed, f)

print("Payload built OK")
PYEOF

# Inject git activity field if any
if [ -n "$GIT_LINES" ]; then
  python3 - "$PAYLOAD_FILE" "$GIT_LINES" <<'PYEOF2'
import json, sys

payload_file = sys.argv[1]
git_lines = sys.argv[2].replace("\\n", "\n").strip()

with open(payload_file) as f:
    embed = json.load(f)

embed["embeds"][0]["fields"].append({
    "name": "💾 Code Activity",
    "value": git_lines[:1020] if git_lines else "_No commits_",
    "inline": False
})

with open(payload_file, "w") as f:
    json.dump(embed, f)
PYEOF2
fi

# ─── Output or post ───────────────────────────────────────────────────────────
if [ "$DRY_RUN" = "true" ]; then
  echo "=== DRY RUN — Discord payload ==="
  cat "$PAYLOAD_FILE" | python3 -m json.tool
  exit 0
fi

HTTP_STATUS=$(curl -s -o /tmp/discord-digest-response.txt -w "%{http_code}" \
    -X POST "$DISCORD_WEBHOOK" \
    -H "Content-Type: application/json" \
    --data-binary "@$PAYLOAD_FILE")

if [ "$HTTP_STATUS" -eq 204 ] || [ "$HTTP_STATUS" -eq 200 ]; then
    echo "✅ Weekly digest posted to Discord (HTTP $HTTP_STATUS)"
else
    echo "❌ Discord post failed (HTTP $HTTP_STATUS)"
    cat /tmp/discord-digest-response.txt
    exit 1
fi
